---
- name: Backup ACLS
  hosts: all
  gather_facts: yes

  tasks:
    - name: Gather the existing configuration
      arista.eos.eos_acls:
        state: gathered
      register: aacls

    - name: Merge provided configuration with device configuration
      arista.eos.eos_acls:
        config:
          - afi: ipv4
            acls:
              - name: test1
                aces:
                  - sequence: 35
                    grant: deny
                    protocol: ospf
                    source:
                      subnet_address: 20.0.0.0/8
                    destination:
                      any: true
        state: merged
