---
- name: Backup ACLS
  hosts: all
  gather_facts: yes
  vars:
    acl_name: "test1"
    subnet_address: "20.0.0.0/8"
    protocol: "ospf"
    grant_rule: "deny"
    sequence: 35
    dany: true

  tasks:
    - name: Gather the existing configuration
      arista.eos.eos_acls:
        state: gathered
      register: aacls

    - name: Merge provided configuration with device configuration
      arista.eos.eos_acls:
        config:
          - afi: ipv4
            acls:
              - name: "{{ acl_name }}"
                aces:
                  - sequence: "{{ sequence }}"
                    grant: "{{ grant_rule }}"
                    protocol: "{{ protocol }}"
                    source:
                      subnet_address: "{{  subnet_address  }}"
                    destination:
                      any: "{{ dany }}"
        state: merged
