---
- name: reboot arista eos router
  hosts: all
  gather_facts: false
  tasks:
    - name: reboot device
      cli_command:
        command: reload now

    - name: reset the connection
      meta: reset_connection

    - name: wait for network device to come back up
      wait_for_connection:
        delay: 10

    - name: grab the uptime
      cli_command:
        command: show ver | i Uptime
      register: uptime

    - name: show uptime
      debug:
        msg: "{{uptime.stdout}}"
