---
- name: Backup ACLS
  hosts: all
  gather_facts: yes

  tasks:
    - name: Gather the existing configuration
      arista.eos.eos_acls:
        state: gathered
      register: aacls

    - ansible.builtin.debug:
        msg: "{{ aacls }}"

    - name: configurable backup path
      arista.eos.eos_config:
        src: eos_template.j2
        backup: yes
        backup_options:
          filename: backup.cfg
          dir_path: ~/
