---
- name: snmp ro/rw string configuration
  hosts: all
  gather_facts: no

  tasks:

    - name: Gather the existing configuration
      arista.eos.eos_acls:
        state: gathered
      register aacls

    - name: Print debug message
      debug:
        msg: "{{ aacls }}"