---
# This playbook prints a simple debug message
- name: Echo
  hosts: all
  gather_facts: true
  vars:
    mymessage: "hello world"

  tasks:
    - name: run multiple commands on remote nodes
      cisco.ios.ios_command:
      commands:
        - show version
        - show interfaces
