---
- name: snmp ro/rw string configuration
  hosts: all
  gather_facts: no

  tasks:
    - name: ensure that the desired snmp strings are present
      cisco.ios.config:
        commands:
          - no snmp-server community ansible-public RO
          - no snmp-server community ansible-private RW
