---
- name: snmp ro/rw string configuration
  hosts: all
  gather_facts: no

  tasks:
    - name: Sending an e-mail using Gmail SMTP servers
      community.general.mail:
        host: smtp.gmail.com
        port: 587
        username: { { mail_username } }
        password: { { mail_password } }
        to: John Smith <john.smith@example.com>
        subject: Ansible-report
        body: System {{ ansible_hostname }} has been successfully provisioned.
      delegate_to: localhost
