---
- name: run multiple commands on remote nodes
  cisco.ios.ios_command:
    commands:
      - show run full
      # - show version
      # - show interfaces
  register: cisconfig

- name: Storing running config
  ansible.builtin.set_stats:
    data:
      BKP_RUNNING_CONFIG: "{{ cisconfig.stdout[0] }}"
    aggregate: no

- name: Print debug
  debug:
    msg: "{{ cisconfig.stdout[0] }}"
