---
- name: run multiple commands on remote nodes
  cisco.ios.ios_command:
    commands:
      - show run
      # - show version
      # - show interfaces
  register: cisconfig

- name: Print debug
  debug:
    msg: "{{ cisconfig }}"
